### PR TITLE
don't indent testset blocks

### PR DESCRIPTION
**Pull request by ZacLN**

### CODE REVIEW

**Comment by pfitzseb** [comment]
What's wrong with indenting `@testset`s?

**Comment by ZacLN** [comment]
I thought the feeling was they shouldn't be indented a they're likely to be highly nested?

**Comment by pfitzseb** [comment]
Fair enough. Base does indent testsets though. Anyways, I don't feel particularly strongly about this.

**Comment by davidanthoff** [comment]
> Fair enough. Base does indent testsets though.

Oh, interesting, I wasn't aware of that. That seems like a pretty strong reason to actually keep the indenting?

**Comment by ZacLN** [comment]
Can't say I feel particularly strongly about this so happy to be guided by others

**Comment by davidanthoff** [comment]
I think generally following Julia base is a good idea for these things. I also don't feel strongly one way or the other, so just following the lead of the core seems an easy way to decide this.

We could leave this PR open and eventually add an option to configure this?

**Pull request closed without merging**
